config/routes.rb
Rails.application.routes.draw do
  root to: 'pins#index'

  resources :pins
  resources :users

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user, required: true

  include PinUploader::Attachment(:image)

  scope :recently_created, -> { order(created_at: :desc) }

  validates :title, :link, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pins, dependent: :destroy

  validates :uid, :nickname, presence: true

  before_save :set_first_admin

  private

  def set_first_admin
    return if User.where(admin: true).where.not(uid: 'akash').any?

    self.admin = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    return unless session[:user_id].present?

    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def require_user
    return if current_user

    redirect_to root_path, flash: { alert: 'Please login first' }
  end

  def require_admin
    return if current_user&.admin?

    redirect_to root_path, flash: { alert: 'Admin user required' }
  end
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  def callback
    auth_info = request.env['omniauth.auth']
    @current_user = User.find_or_create_by(uid: auth_info[:uid]) do |user|
      user.nickname = auth_info[:extra][:raw_info][:nickname]
    end
    session[:user_id] = @current_user.id

    redirect_to root_path
  end

  def failure
    @error_msg = request.params['message']
  end

  def logout
    reset_session
    redirect_to logout_url
  end

  private

  def logout_url
    request_params = {
      returnTo: root_url,
      client_id: ENV['AUTH0_ID']
    }

    URI::HTTPS.build(host: ENV['AUTH0_DOMAIN'], path: '/v2/logout', query: to_query(request_params)).to_s
  end

  def to_query(hash)
    hash.map { |k, v| "#{k}=#{CGI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :require_user, except: :index

  def index
    @pins = find_pins
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = current_user.pins.create(pin_params)
    @pins = find_pins
  end

  def edit
    @pin = Pin.find(params[:id])
    render 'new'
  end

  def update
    @pin = Pin.find(params[:id])
    if @pin.user == current_user || current_user.admin?
      @pin.update(pin_params)
      @pins = find_pins
      render 'create'
    else
      raise ActionNotFound
    end
  end

  def destroy
    @pin = Pin.find(params[:id])
    if @pin.user == current_user || current_user.admin?
      @pin.destroy
      redirect_to root_path, flash: { notice: 'Pin deleted' }
    else
      redirect_to root_path, flash: { alert: 'You cannot delete that pin' }
    end
  end

  private

  def find_pins
    pins = Pin.recently_created.includes(:user).page(params[:page]).per(12)
    return pins unless params[:user_id].present?

    pins.where(user_id: params[:user_id])
  end

  def pin_params
    params.require(:pin).permit(:title, :description, :link, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.order(id: :desc)
  end

  def update
    @user = User.find(params[:id])
    @user.update(permitted_params)
    redirect_to users_path, flash: { notice: 'User updated' }
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, flash: { notice: 'User deleted' }
  end

  private

  def permitted_params
    params.require(:user).permit(:admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'card text-white bg-danger mb-3') do
        concat(content_tag(:div, class: 'card-header') do
          concat(content_tag(:h5) do
            concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: 'card-body') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Akash on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        Akash on Rails
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li>
          <%= link_to 'Home', root_path, class: 'nav-link px-2 link-secondary' %>
        </li>
        <% if current_user %>
          <li>
            <%= link_to 'My Pins', pins_path(user_id: current_user.id), class: 'nav-link px-2 link-secondary' %>
          </li>
        <% end %>
        <% if current_user&.admin? %>
          <li>
            <%= link_to 'Users', users_path, class: 'nav-link px-2 link-secondary' %>
          </li>
        <% end %>
        <li>
          <%= link_to 'About', '#', class: 'nav-link px-2 link-secondary' %>
        </li>
      </ul>

      <div class="col-md-3 text-end">
        <% if current_user %>
          <div class="btn-group pl-5">
            <%= link_to 'Add pin', new_pin_path, remote: true, class: 'btn btn-primary' %>
          </div>
          <div class="btn-group pl-5">
            <%= button_to 'Logout', '/auth/logout', method: :get, class: 'btn btn-outline-primary me-2' %>
          </div>
        <% else %>
          <%= button_to 'Login', '/auth/auth0', method: :post, class: 'btn btn-outline-primary me-2' %>
        <% end %>
      </div>
    </header>

    <main class="container">
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous" data-turbolinks-track="none"></script>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {id: 'pinForm'}, remote: true do |f| %>
  <%= errors_for(@pin) %>
  <div class="modal-body">
    <%= f.hidden_field :image, value: @pin.cached_image_data %>
    <div class="mb-3">
      <%= f.label :title, 'Title', class: 'form-label' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :description, 'Description', class: 'form-label' %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :link, 'Link', class: 'form-label' %>
      <%= f.text_field :link, class: 'form-control' %>
    </div>
    <div class="mb-3">
      <%= f.label :image, 'Image', class: 'form-label' %>
      <%= f.hidden_field :image, value: @pin.cached_image_data %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end  %>

app/views/pins/_modal.html.erb
<div class="modal fade" id="pinModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add pin</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/pins/_pins.html.erb
<% if @pins.any? %>
  <div id="pinList" class="row row-cols-4 grid">
    <% @pins.each do |pin| %>
      <div class="col">
        <div class="card mb-4">
          <%= link_to pin.link, target: :blank do %>
            <%= image_tag pin.image_url(:small), class: 'card-img-top' if pin.image(:small) %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= pin.title %></h5>
            <h6><small>by <%= link_to pin.user.nickname, pins_path(user_id: pin.user_id) %></small></h6>
            <p class="card-text"><%= pin.description %></p>
            <div class="btn-toolbar">
              <div class="btn-group me-2">
                <%= link_to 'Visit', pin.link, class: 'btn btn-primary', target: :blank %>
              </div>
              <% if current_user && (current_user.admin? || pin.user == current_user) %>
                <div class="btn-group me-2">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                    Actions
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><%= link_to 'Edit', edit_pin_path(pin), remote: true, class: 'dropdown-item' %></li>
                    <li><%= link_to 'Delete', pin_path(pin), method: :delete, class: 'dropdown-item', data: {confirm: 'Are you sure you want to delete this pin?'} %></li>
                  </ul>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @pins, theme: 'twitter-bootstrap-4', nav_class: "pinPagination" %>
  <div class="page-load-status mb-5 mt-5">
    <div class="infinite-scroll-request text-center">
      <div class="spinner-border text-danger" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>
    <p class="infinite-scroll-last text-center"><em>End of content</em></p>
    <p class="infinite-scroll-error text-center"><em>No more pages to load</em></p>
  </div>
<% else %>
  <p class="text-center"><em>No pins found</em></p>
<% end %>

app/views/pins/create.js.erb
<% if @pin.errors.any? %>
  $('#pinForm').replaceWith("<%= j render "pins/form" %>");
<% else %>
  $('#pinList').replaceWith("<%= j render "pins/pins" %>");
  $('#pinModal').modal('toggle');
<% end %>

app/views/pins/index.html.erb
<%= render "pins" %>

app/views/pins/new.js.erb
$('#pinModal').remove();
$('body').append('<%= j render "pins/modal" %>');  // Append modal
$('#pinModal').modal('toggle'); // Toggle modal

app/views/pins/update.js.erb
<% if @pin.errors.any? %>
  $('#pinForm').replaceWith("<%= j render "pins/form" %>");
<% else %>
  $('#pinModal').modal('toggle'); // Toggle modal
<% end %>

app/views/users/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nickname</th>
      <th scope="col">Admin</th>
      <th scope="col">Pins</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <th scope="row"><%= user.id %></th>
        <td><%= user.nickname %></td>
        <td><%= raw user.admin? ? '<i class="bi bi-check"></i>' : '<i class="bi bi-x"></i>' %></td>
        <td><%= link_to user.pins.count, pins_path(user_id: user.id) %></td>
        <td>
          <div class="btn-group me-2">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <% if user.admin? %>
                <li><%= button_to 'Remove admin', user_path(user.id), params: {user: {admin: false}}, method: :patch, class: 'dropdown-item' %></li>
              <% else %>
                <li><%= button_to 'Make admin', user_path(user.id), params: {user: {admin: true}}, method: :patch, class: 'dropdown-item' %></li>
              <% end %>
              <li><%= link_to 'Delete', user_path(user), method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>